version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    depends_on:
      - ocr-service
      - ia-classifier
      - distribution-service

  ocr-service:
    build: ./microservices/ocr-service
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  ia-classifier:
    build: ./microservices/ia-classifier-service
    ports:
      - "6000:6000"
    env_file:
      - ./backend/.env

  distribution-service:
    build: ./microservices/distribution-service
    ports:
      - "7000:7000"


    

